markdown: kramdown 
highlighter: rouge
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: DF-Kyun
author: "kyun"
email: dfkyun@gmail.com
name: "kyun's Blog"
baseurl: /
url: https://df-kyun.github.io
domain: https://df-kyun.github.io

all_categories: [
["program", "软件编程","/posts/program.html"],
["web", "Web建站","/posts/web.html"],
["linux", "Linux相关","/posts/linux.html"],
["read", "读书笔记","/posts/read.html"],
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 4
paginate_path: "posts/page:num"
timezone: Asia/Shanghai

gems: [jekyll-paginate]
 
collections:
  docs:
    output: true


